require("user.general")
require("user.keymap")
require("user.plugin-manager")
require("user.themes").set_theme("nordic")
require("user.lspz")
require("user.cmp")
require("user.treesitter")
require("user.telescope")
require("user.neotree")
require("user.autopair")
require("user.lualine")
require("user.tabline")
require("user.conform")

